version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=reservation_db
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=reservation_db
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
